# Generated by Django 4.0.4 on 2022-06-08 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=225)),
                ('password', models.CharField(max_length=225)),
                ('username', models.CharField(max_length=225)),
                ('address', models.CharField(max_length=225)),
                ('age', models.IntegerField()),
                ('images', models.ImageField(null=True, upload_to='image/')),
                ('phone', models.CharField(max_length=225)),
            ],
        ),
    ]
