# Generated by Django 4.0.4 on 2022-06-08 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthApp', '0003_remove_patient_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='patient',
        ),
    ]
