# Generated by Django 4.0.4 on 2022-06-08 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthApp', '0005_patient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='patient',
        ),
    ]
