# Generated by Django 4.0.4 on 2022-06-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthApp', '0006_delete_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('address', models.CharField(max_length=225)),
                ('gender', models.CharField(max_length=225)),
                ('age', models.IntegerField()),
                ('phone', models.CharField(max_length=225)),
                ('bloodgroup', models.CharField(max_length=225)),
            ],
        ),
    ]
