# Generated by Django 4.0.4 on 2022-06-08 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthApp', '0009_remove_patient_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='patientemmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='healthApp.patient')),
            ],
        ),
    ]
