# Generated by Django 4.0.4 on 2022-06-08 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthApp', '0010_patientemmail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='patientemmail',
            new_name='patientemail',
        ),
    ]
