# Generated by Django 4.0.4 on 2022-06-08 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthApp', '0011_rename_patientemmail_patientemail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='patientemail',
        ),
    ]
