# Generated by Django 4.0.4 on 2022-06-08 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthApp', '0012_delete_patientemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='appoinment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('address', models.CharField(max_length=225)),
                ('gender', models.CharField(max_length=225)),
                ('age', models.IntegerField()),
                ('phone', models.CharField(max_length=225)),
                ('bloodgroup', models.CharField(max_length=225)),
                ('email', models.EmailField(max_length=254)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='healthApp.designation')),
            ],
        ),
    ]
